import { db } from "./index";
import { fuelLogs, orders, transactions } from "./schema";
import { eq } from "drizzle-orm";
import { IncomingFuelLog } from "../types";

/**
 * processSyncBatch
 * This is the "Idempotency Engine." It ensures that even if a phone retries
 * a sync due to a poor connection, we never create duplicate records.
 */
export const processSyncBatch = async (logs: IncomingFuelLog[]) => {
  let processedCount = 0;

  for (const log of logs) {
    try {
      // 1. IDEMPOTENT INSERT
      // We target 'mobileOfflineId' (the unique ID generated by the phone).
      // If this ID already exists in Postgres, Drizzle will skip the insert.
      await db.insert(fuelLogs).values({
        mobileOfflineId: log.mobileOfflineId,
        userId: log.userId, // UUID string from mobile
        volumeDispensed: log.volume.toString(), // Numeric columns require strings in Drizzle
        locationLat: log.lat?.toString() || null,
        locationLng: log.lng?.toString() || null,
        dispensedAt: new Date(log.timestamp),
        syncStatus: "completed"
      }).onConflictDoNothing({ target: fuelLogs.mobileOfflineId });

      // 2. ORDER STATUS UPDATE
      // If the log is tied to a specific Order, we update that order's 
      // final volume and move it to 'delivered' status.
      if (log.orderId) {
        // The check 'if (log.orderId)' ensures it is not null.
        // We cast 'as string' to match the Primary Key type in orders table.
        await db.update(orders)
          .set({ 
            measurementFinalVolume: log.volume.toString(),
            status: "delivered" 
          })
          .where(eq(orders.id, log.orderId as string));
      }

      processedCount++;
    } catch (error) {
      // We catch errors per-log so one failure doesn't kill the entire batch.
      console.error(`❌ Sync error for log ${log.mobileOfflineId}:`, error);
    }
  }

  return processedCount;
};

/**
 * finalizeOrderPayment
 * Handles the financial settlement logic using a Database Transaction.
 * Ensures the Transaction and Order are updated together as a single unit.
 */
export const finalizeOrderPayment = async (pgOrderId: string, pgPaymentId: string) => {
  return await db.transaction(async (tx) => {
    // 1. Update the Transaction record
    // We match on the pgOrderId (Razorpay/Internal ID) generated during handshake
    const [updatedTxn] = await tx.update(transactions)
      .set({ 
        status: "SUCCESS", 
        pgPaymentId: pgPaymentId, 
        paidAt: new Date() 
      })
      .where(eq(transactions.pgOrderId, pgOrderId))
      .returning();

    if (!updatedTxn) {
      throw new Error(`Transaction ${pgOrderId} not found.`);
    }

    // 2. Update the master Order status to 'paid'
    // We use 'as any' here to bridge internal Drizzle UUID types safely.
    await tx.update(orders)
      .set({ status: "paid" })
      .where(eq(orders.id, updatedTxn.orderId as any));

    return updatedTxn;
  });
};